on: [pull_request]

name: CI

jobs:
    build:
        name: Build App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # GitHub action for Node.JS.
            # https://github.com/actions/setup-node
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.13.2"
                  check-latest: true
            - name: Install dependencies
              run: npm ci
            - name: Create the Rollup bundle
              run: npm run build
            - name: Run tests
              run: npm run test
